
yolo:
	g++ YOLO.cpp -std=c++17 \
	-I/home/justin/Documentos/opencv/opencvi/include/opencv4/ \
	-L/home/justin/Documentos/opencv/opencvi/lib/ \
	-lopencv_core \
	-lopencv_imgproc \
	-lopencv_imgcodecs \
	-lopencv_highgui \
	-lopencv_video \
	-lopencv_videoio \
	-lopencv_dnn \
	-lopencv_dnn_superres \
	-o visionYOLO.bin


runY:
	./visionYOLO.bin